version: "3.8"

services:
  music_bot:
    build: .
    container_name: discord_music_bot
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true
    network_mode: host
